services:
  neo4j:
    image: neo4j:5-community
    container_name: frc_neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/12345678
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports:
      - '7474:7474' # Browser UI
      - '7687:7687' # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - frc_network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:7474',
        ]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  frc_network:
    name: frc_network
    driver: bridge
