name: CI

on:
  push:
    branches: [ main, master, dev, feat/auth ]
  pull_request:
    branches: [ main, master, dev, feat/auth ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: frc_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: npx prisma generate --schema=./prisma/schema/base.prisma

      - name: Run Unit Tests
        run: pnpm test
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5433/frc_db?schema=public
          JWT_SECRET: frc@dev#jwt!S3cr3t$2026^access&secure*key
          JWT_REFRESH_SECRET: frc@dev#jwt!R3fr3sh$2026^refresh&secure*key
          BCRYPT_SALT_ROUNDS: 10
          REDIS_HOST: localhost
          REDIS_PORT: 6379
